services:
  jupyterlab:
    image: lab3docker
    env_file: 
      - .env
    ports:
      - "8890:8888"
    volumes:
      - ./:/Lab3
      - ./settings.txt:/root/.jupyter/lab/user-settings/@jupyterlab/notebook-extension/tracker.jupyterlab-settings
    networks:
      - lab3network
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports: 
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - lab3network

volumes:
  postgresdata:

networks:
  lab3network: